### ISSUE TITLE
Maximum duration not taken into account

### ISSUE THREAD

**Issue by Gdemaude** [wefatherley/monte-carlo#1]
Hello, I noticed that the arg max_duration is not properly taken into account when running the code. Here is the fix:
`
        def exit(self):

        if self.max_duration is not None:
            if self["time"][-1] >= self.max_duration:
                return True
        if len(self.events) == 0:
            return True
        else:
            return False
`

**Comment by wfatherley** [comment]
Thanks for finding that :)
